---
- hosts: default
  become: True
  tasks:
    - name: "Save vhosts list"
      set_fact:
        vhosts_list: "{{ vhosts.split() }}"

    - name: Add epel-release
      yum:
        name: epel-release
        state: present
  
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: "Create parent directories"
      file:
        path: "/var/www/{{ item }}/html"
        state: directory
        mode: '0755'
      loop: "{{ vhosts_list }}"

    - name: "Template index.html"
      template:
        dest: "/var/www/{{ item }}/html/index.html"
        src: index.html.j2
      loop: "{{ vhosts_list }}"

    - name: "Template server block files"
      template:
        dest: "/etc/nginx/conf.d/{{ item }}.conf"
        src: server.conf.j2
      loop: "{{ vhosts_list }}"

    - name: "Enable NGINX service"
      service:
        name: nginx
        state: started
        enabled: yes